### ISSUE TITLE
R and packages version?

### ISSUE THREAD

**Issue by PSobrevalsAlcaraz** [jn-goe/gruffi#13]
Hello,

I am trying to install gruffi in my computer and while installing the dependencies, it keeps complaining that some functions are not available. I cannot figure out the proper versions, could someone share the R and the packages/dependencies versions? I believe this could be the issue.

Thank you for your time,
Paula

**Comment by tupaquito** [comment]
Hello, I have a similar issue:
I recently installed this package and dependencies in R 4.3 and encountered the foloowing error message:

```r
Error: package or namespace load failed for ‘MarkdownHelpers’:
 object ‘as.numeric.wNames.factor’ is not exported by 'namespace:CodeAndRoll2'
Execution halted


ERROR: lazy loading failed for package ‘gruffi’
* removing ‘/.../gruffi’
```

I tried to install again the dependencies (trying different versions) in Mac and Linux. However, this error or similars regarding the 'MarkdownHelpers' package persisted.

Thank you in advance

**Comment by vertesy** [comment]
Hey, very sorry I did not see the issue earlier. 

@PSobrevalsAlcaraz: Could you please be specific? "some functions"

@tupaquito: Thanks for reporting. I updated CodeAndRoll2, but `as.numeric.wNames.factor()` is a correctly called - I see it at least. Maybe it has been resolved?

**Comment by tupaquito** [comment]
> Hey, very sorry I did not see the issue earlier.
> 
> @PSobrevalsAlcaraz: Could you please be specific? "some functions"
> 
> @tupaquito: Thanks for reporting. I updated CodeAndRoll2, but `as.numeric.wNames.factor()` is a correctly called - I see it at least. Maybe it has been resolved?

Hi, thanks for answering. Now, the function 'as.numeric.wNames.factor()' is correctly called, but it prompts a new error:

```
Error: object ‘stopif’ is not exported by 'namespace:MarkdownHelpers'
Execution halted
ERROR: lazy loading failed for package ‘gruffi’
* removing ‘/home/alex/R/x86_64-pc-linux-gnu-library/4.3/gruffi’
Warning: installation of package ‘/tmp/RtmpPM2hbh/filea45cc66d0349/gruffi_1.0.2.tar.gz’ had non-zero exit status> 
```
Thanks again

**Comment by vertesy** [comment]
Thank you for the feedback! 
Yes I also got that yesterday, but then it disappeared. I will take a 2nd look.

**Comment by vertesy** [comment]
I think I fixed it, but I am making some other changes as well, will post here when updated.

**Comment by vertesy** [comment]
Ok, I believe it is fixed with a new major version that I uploaded. Please let me know if otherwise.

**Comment by bobermayer** [comment]
I still have this issue in a completely new R environment (R4.3.2): 
installing the Bioconductor packages works, `Stringendo`, `CodeAndRoll2` and `ReadWriter` are ok too, but then
```
devtools::install_github(repo = "vertesy/MarkdownHelpers", upgrade = F)
```
fails with `Error: object ‘as.numeric.wNames.factor’ is not exported by 'namespace:CodeAndRoll2'`

**Comment by vertesy** [comment]
Sorry, misread it. I found .
Working on a fix, not yet solved.
Thanks for raising it and sorry for the inconvenience.

This is actually an issue in `MarkdownHelpers()` not `gruffi()` please next time raise the issue in the repo the problem belongs to. Not needed now anymore.

~~Please try to install the latest `MarkdownHelpers()`. It installs for me without an error.~~

**Comment by vertesy** [comment]
Ok, acted to hastily and changed stuff before checking if the problem exist. Thereby, I actually introduced a problem, that was not there before. 

Now it is fixed, basically back to the original state.

Conclusion is:

1. I do not see your problem. Packages install correctly on my end.
2. `as.numeric.wNames.factor` is a legit function exported from `CodeAndRoll2`.

To proceed, as I originally suggested, 3 h ago:

1. Uninstall all vertesy packages
2. Install all vertesy packages 
3. If problem exists, send `session_info()` output.

I know it's unsatisfying, but things work when I install freshl.

**Comment by bobermayer** [comment]
hi, thanks for you replies and for looking into it.
I followed your advice, removed the `vertesy` packages, and istalling the most recent version of `CodeAndRoll2` helps.
the issue is in the `gruffi` readme: it recommends to install version `v2.3.4`

and I  additionally had to do install `EnhancedVolcano` from Bioconductor, `DatabaseLinke.R` from github, and `raster` from CRAN.

one more thing: `GOscoreEvaluation` failed with Seurat v5, because of the new layer structure. I went back to v4 for now

**Comment by vertesy** [comment]
Hi,

1. Fixed the readme. will update soon.
2. As for ` EnhancedVolcano, DatabaseLinke.R`
   -  This I believe is an issue at installing `Seurat.utils`, bc none is used in `gruffi`.
   - `Seurat.utils` suggests to install these in the DESCRIPTION file: ` suggests = "SoupX, princurve, EnhancedVolcano, DatabaseLinke.R"` but that _should not be a requirement for installation_. Not sure about this.
3. As for ` raster`
   - `gruffi` declares `raster` as `imports` in the DESCRIPTION file, [which also seems correct, and it should  automatically be co-installed](https://r-pkgs.org/description.html#sec-description-imports-suggests).

**Comment by vertesy** [comment]
In the upcoming v1.2.7 `raster, viridis, rgl, htmlwidgets, sm` will not removed as dependencies, and instead become `suggest` along with making an unused functional an optional extra.
